### ISSUE TITLE
pygatt not working

### ISSUE THREAD

**Issue by enlight3d** [hbldh/pymetawear#18]
Hello, I was using your previous version since last week (the original 5.0 which was on develop, not the 5.0a1) but as I've seen your latest commits, I wanted to update to the latest working version. I tried master, develop and then figured out that I maybe needed to try pygatt-py3 which is the version that I'm on now. Only problem is that even when loading your examples (accelerometer for example) well I have this error (see image).

![2016-09-14-121616_1920x1080_scrot](https://cloud.githubusercontent.com/assets/19186686/18508614/20e862e4-7a75-11e6-8472-94305f99c444.png)

It seems to ask for latest pygatt+gatttool (which are already installed !) so I don't get it. On master branch I had an error with "basestring" not being defined. If you need more infos about this one too let me know.

I'm on a raspberry pi 3 with latest jessie version.

**Comment by hbldh** [comment]
The `pygatt-py3` branch is a preemptive branch, preparing for predicted changes in the next `pygatt` release (it cannot be used right now except with the `python-3-tests` branch of `pygatt`), so avoid that one.

The problem you encountered is however closely related to that. Apparently I had mistakenly removed an overriding method that monkey-patched that `basestring` error in `pygatt` to early. I have replaced it now in both develop and master branch (version 0.5.0a3) and tested it on my RPi 2 with Jessie and Python 3.4.

**Comment by enlight3d** [comment]
okay thanks !
