### ISSUE TITLE
Bluetooth RSSI value

### ISSUE THREAD

**Issue by Amanddn** [hbldh/pymetawear#19]
Hi,
Is there a way to get bluetooth RSSI value using pymetawear or some other dependent libraries ?

Thanks in advance.

Aman.

**Comment by hbldh** [comment]
I am not sure that it can be done in simpel enough way in Python.

There is [this StackOverflow](https://stackoverflow.com/questions/24417017/bluetooth-le-signal-strength-linux) that discusses several techniques.
My best bet: Running `btmon` doing a `hcitool lescan` in a subprocess might work, but btmon requires `sudo` privileges.
