### ISSUE TITLE
Reading analog input

### ISSUE THREAD

**Issue by wliao229** [hbldh/pymetawear#27]
Would pymetawear be able to read analog signal from the board? I had a pulse sensor attached to it, and I was wondering if it is possible to read the signal through python.

**Comment by jhennrich** [comment]
Check out the gpio branch of the kinemic fork:
https://github.com/kinemic/pymetawear/tree/gpio

There is also code for events and timers:
https://github.com/kinemic/pymetawear/tree/events_timers

Both are untested and undocumented but should work.

**Comment by wliao229** [comment]
Thanks! That’s really helpful.

**Comment by hbldh** [comment]
Nice! Should those modules work fine, feel free to send Pull Requests for them!
