### ISSUE TITLE
Bluetooth connection fails

### ISSUE THREAD

**Issue by cb2411** [hbldh/pymetawear#41]
Established connection (pygatt or pybluez) fails after random periods of time - particularly short if connected to multiple metawears and using acc, mag, gyr.

**Comment by hbldh** [comment]
I am aware of this, but it is nothing I can do from PyMetaWear. All connection handling is in the backend packages, and nothing I can improve by making changes in PyMetaWear.

If you need multiple MetaWears connected and handle multiple signals I would use iOS or Android libraries instead; Bluetooth LE on mobile is much more stable in my experience.
