### ISSUE TITLE
Minor mistake on documentation

### ISSUE THREAD

**Issue by josuetleoro** [hbldh/pymetawear#57]
* pymetawear version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
I just wanted to let you know there is a minor mistake in the documentation. For the discovering addresses API example you import from "pymetawear.client". Not sure if there was some change on the code of client.py, but the discovery_devices() method is on the discover.py file. Therefore the example should import from "pymetawear.discover"

**Comment by hbldh** [comment]
Thank you, will be correcting this soon!
